# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Model', [dirname(__file__)])
        except ImportError:
            import _Model
            return _Model
        if fp is not None:
            try:
                _mod = imp.load_module('_Model', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Model = swig_import_helper()
    del swig_import_helper
else:
    import _Model
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Model(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Model, name)
    __repr__ = _swig_repr
    __swig_setmethods__["a"] = _Model.Model_a_set
    __swig_getmethods__["a"] = _Model.Model_a_get
    if _newclass:a = _swig_property(_Model.Model_a_get, _Model.Model_a_set)
    __swig_setmethods__["omega"] = _Model.Model_omega_set
    __swig_getmethods__["omega"] = _Model.Model_omega_get
    if _newclass:omega = _swig_property(_Model.Model_omega_get, _Model.Model_omega_set)
    __swig_setmethods__["gamma"] = _Model.Model_gamma_set
    __swig_getmethods__["gamma"] = _Model.Model_gamma_get
    if _newclass:gamma = _swig_property(_Model.Model_gamma_get, _Model.Model_gamma_set)
    __swig_setmethods__["delta_t"] = _Model.Model_delta_t_set
    __swig_getmethods__["delta_t"] = _Model.Model_delta_t_get
    if _newclass:delta_t = _swig_property(_Model.Model_delta_t_get, _Model.Model_delta_t_set)
    __swig_setmethods__["I"] = _Model.Model_I_set
    __swig_getmethods__["I"] = _Model.Model_I_get
    if _newclass:I = _swig_property(_Model.Model_I_get, _Model.Model_I_set)
    def calc(self, *args): return _Model.Model_calc(self, *args)
    def __init__(self): 
        this = _Model.new_Model()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Model.delete_Model
    __del__ = lambda self : None;
Model_swigregister = _Model.Model_swigregister
Model_swigregister(Model)

# This file is compatible with both classic and new-style classes.


